{"uuid": "777e8d90-86bf-4c58-8aa3-2576ad2af306", "children": ["51b5483a-c229-4e64-bb00-ea0a14fae594"], "befores": [{"name": "getdata", "status": "broken", "statusDetails": {"message": "NameError: name 'data' is not defined\n", "trace": "  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/test/work/API_Automation/TestCase/test_login.py\", line 28, in getdata\n    self.urls = data.url\n"}, "start": 1586937531939, "stop": 1586937532089}], "start": 1586937531939, "stop": 1586937532191}